import numpy as np
data = np.arange(0, 20)
print('\nThe Original Array List: ')
print(data)
row_number1 = np.mean(data)
row_number2 = np.average(data)
assert np.allclose(row_number1, row_number2)
print('\nThe Mean Is: ',  row_number1)
row_number1 = np.std(data)
row_number2 = np.sqrt(np.mean((data - np.mean(data))**2))
assert np.allclose(row_number1, row_number2)
print('\nStandard Deviation: ', 1)
row_number1 = np.var(data)
row_number2 = np.mean((data - np.mean(data))**2)
assert np.allclose(row_number1, row_number2)
print('\nThe Variance Is: ', row_number1)
